# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Latitude', models.CharField(max_length=200)),
                ('Longitude', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('Representative', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Org',
                'verbose_name_plural': 'Org',
            },
        ),
    ]
