# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='ParentId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='order.Area'),
        ),
    ]
