# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-26 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='org',
            options={},
        ),
    ]
