# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-26 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20180326_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'verbose_name': 'Org', 'verbose_name_plural': 'Org'},
        ),
    ]
