# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-26 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180326_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('ParentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentid', to='order.PurchaseCategory')),
            ],
            options={
                'verbose_name': 'PurchaseCategory',
                'verbose_name_plural': 'PurchaseCategory',
            },
        ),
    ]
