# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-26 05:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0007_purchasecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OrderDate', models.DateField(auto_now=True)),
                ('WayToPay', models.CharField(max_length=300)),
                ('PaymentTime', models.DateTimeField(auto_now=True)),
                ('Receipts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quality', models.IntegerField()),
                ('RefundOperator', models.CharField(max_length=100)),
                ('RefundAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RefundFrom', models.CharField(max_length=200)),
                ('RefundTime', models.DateTimeField(auto_now=True)),
                ('AmountBeforePayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OrderDetail',
                'verbose_name_plural': 'OrderDetail',
            },
        ),
    ]
