# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Second', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Third', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fourth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fifth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Sixth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Seventh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FirstRecommended', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RatiofReceiptsAndBonuspoint', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RatiofBonuspointReward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PayerHasBonuspoint', models.BooleanField(default=False)),
                ('RefundDeadline', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'BonusPoints',
                'verbose_name_plural': 'BonusPoints',
            },
        ),
    ]
