# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-26 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_bonuspoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='UserId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL),
        ),
    ]
